<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ElementsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('elements')->insert([
            [
                'type' => 2,
                'sub_type' => 1,
                'name' => 'glucose',
                'aka' => null,
                'names' => null,
                'description' => 'Glucose comes from the Greek word for \"sweet.\" It\'s a type of sugar you get from foods you eat, and your body uses it for energy. As it travels through your bloodstream to your cells, it\'s called blood glucose or blood sugar. Insulin is a hormone that moves glucose from your blood into the cells for energy and storage.',
                'ref' => 'https://en.wikipedia.org/wiki/Glucose',
            ],
            [
                'type' => 2,
                'sub_type' => 1,
                'name' => 'fructose',
                'aka' => null,
                'names' => null,
                'description' => 'Fructose, or fruit sugar, is a simple ketonic monosaccharide found in many plants, where it is often bonded to glucose to form the disaccharide sucrose. It is one of the three dietary monosaccharides, along with glucose and galactose, that are absorbed directly into blood during digestion.',
                'ref' => 'https://en.wikipedia.org/wiki/Fructose',
            ],
            [
                'type' => 2,
                'sub_type' => 1,
                'name' => 'galactose',
                'aka' => null,
                'names' => null,
                'description' => 'Galactose is a monosaccharide. When combined with glucose (monosaccharide), through a condensation reaction, the result is the disaccharide lactose. The hydrolysis of lactose to glucose and galactose is catalyzed by the enzymes lactase and β-galactosidase. The latter is produced by the lac operon in Escherichia coli.',
                'ref' => 'https://en.wikipedia.org/wiki/Galactose',
            ],
            [
                'type' => 4,
                'sub_type' => 7,
                'name' => 'omega6',
                'aka' => 'Linoleic acid',
                'names' => null,
                'description' => 'Linoleic acid. EFA (Essential Fat Acid) Industry-sponsored studies have suggested that omega-6 fatty acids should be consumed in a 1:1 ratio to omega-3,[31] though it has been observed that the diet of many individuals today is at a ratio of about 16:1, mainly from vegetable oils.[31] Omega-6 and omega-3 are essential fatty acids that are metabolized by some of the same enzymes, and therefore an imbalanced ratio can affect how the other is metabolized.[32] In a study performed by Ponnampalam,[33] it was noticed that feeding systems had a great effect on nutrient content on the meat sold to consumers. Cynthia Doyle conducted an experiment to observe the fatty acid content of beef raised through grass feeding versus grain feeding; she concluded that grass fed animals contain an overall omega-6:omega-3 ratio that is preferred by nutritionists.[32] In today\'s modern agriculture, the main focus is on production quantity, which has decreased the omega-3 content, and increased the omega-6 content, due to simple changes such as grain-feeding cattle.[16] In grain-feeding cattle, this is a way to increase their weight and prepare them for slaughter much quicker compared to grass-feeding. This modern way of feeding animals may be one of many indications as to why the omega-6:omega-3 ratio has increased.',
                'ref' => 'https://en.wikipedia.org/wiki/Omega-6_fatty_acid',
            ],
            [
                'type' => 2,
                'sub_type' => 2,
                'name' => 'sucrose',
                'aka' => null,
                'names' => null,
                'description' => 'Sucrose is a disaccharide sugar made from fructose and glucose molecules. Sucrose needs an enzyme called sucrase to cleave it in half before its components can be absorbed. Sucrose tastes sweet -- which is why it’s used to make granulated table sugar -- but not as sweet as fructose.',
                'ref' => 'https://en.wikipedia.org/wiki/Sucrose',
            ],
            [
                'type' => 2,
                'sub_type' => 2,
                'name' => 'lactose',
                'aka' => null,
                'names' => null,
                'description' => 'Lactase is a protein, an enzyme that is produced in the small intestine. The human body uses lactase to break down lactose into galactose and glucose, which is then absorbed into the bloodstream. If lactase levels are low, the lactose does not break down and it does not absorb into the bloodstream.',
                'ref' => 'https://en.wikipedia.org/wiki/Lactose',
            ],
            [
                'type' => 2,
                'sub_type' => 2,
                'name' => 'maltose',
                'aka' => null,
                'names' => null,
                'description' => 'Maltose is made from two glucose units: Maltose or malt sugar is the least common disaccharide in nature. It is present in germinating grain, in a small proportion in corn syrup, and forms on the partial hydrolysis of starch. It is a reducing sugar.',
                'ref' => 'https://en.wikipedia.org/wiki/Maltose',
            ],
            [
                'type' => 2,
                'sub_type' => 3,
                'name' => 'raffinose',
                'aka' => null,
                'names' => null,
                'description' => 'Raffinose is a trisaccharide composed of galactose, glucose, and fructose. It can be found in beans, cabbage, brussels sprouts, broccoli, asparagus, other vegetables, and whole grains. Raffinose can be hydrolyzed to D-galactose and sucrose by the enzyme α-galactosidase (α-GAL), an enzyme not found in the human digestive tract. α-GAL also hydrolyzes other α-galactosides such as stachyose, verbascose, and galactinol, if present. The enzyme does not cleave β-linked galactose, as in lactose.',
                'ref' => 'https://en.wikipedia.org/wiki/Raffinose',
            ],
            [
                'type' => 2,
                'sub_type' => 3,
                'name' => 'stachyose',
                'aka' => null,
                'names' => null,
                'description' => 'Stachyose is a tetrasaccharide consisting of two α-D-galactose units, one α-D-glucose unit, and one β-D-fructose unit sequentially linked as gal(α1→6)gal(α1→6)glc(α1↔2β)fru. Together with related oligosaccharides such as raffinose, Stachyose occurs naturally in numerous vegetables (e.g. green beans, soybeans and other beans) and other plants.\n\nStachyose is less sweet than sucrose, at about 28% on a weight basis. It is mainly used as a bulk sweetener or for its functional oligosaccharide properties.[1][additional citation(s) needed] Stachyose is not completely digestible by humans and delivers 1.5 to 2.4 kcal/g (6 to 10 kJ/g).',
                'ref' => 'https://en.wikipedia.org/wiki/Stachyose',
            ],
            [
                'type' => 2,
                'sub_type' => 4,
                'name' => 'starch',
                'aka' => null,
                'names' => null,
                'description' => 'Starch or amylum is a polymeric carbohydrate consisting of a large number of glucose units joined by glycosidic bonds. This polysaccharide is produced by most green plants as energy storage. It is the most common carbohydrate in human diets and is contained in large amounts in staple foods like potatoes, wheat, maize (corn), rice, and cassava.\n\nPure starch is a white, tasteless and odorless powder that is insoluble in cold water or alcohol. It consists of two types of molecules: the linear and helical amylose and the branched amylopectin. Depending on the plant, starch generally contains 20 to 25% amylose and 75 to 80% amylopectin by weight.[4] Glycogen, the glucose store of animals, is a more highly branched version of amylopectin',
                'ref' => 'https://en.wikipedia.org/wiki/Starch',
            ],
            [
                'type' => 2,
                'sub_type' => 4,
                'name' => 'glycogen',
                'aka' => null,
                'names' => null,
                'description' => 'Glycogen is a multibranched polysaccharide of glucose that serves as a form of energy storage in humans,[2] animals,[3] fungi, and bacteria.[citation needed] The polysaccharide structure represents the main storage form of glucose in the body.',
                'ref' => 'https://en.wikipedia.org/wiki/Glycogen',
            ],
            [
                'type' => 2,
                'sub_type' => 4,
                'name' => 'cellulose',
                'aka' => null,
                'names' => null,
                'description' => 'Cellulose is an important structural component of the primary cell wall of green plants, many forms of algae and the oomycetes. Some species of bacteria secrete it to form biofilms. Cellulose is the most abundant organic polymer on Earth. The cellulose content of cotton fiber is 90%, that of wood is 40–50%, and that of dried hemp is approximately 57%.',
                'ref' => 'https://en.wikipedia.org/wiki/Cellulose',
            ],
            [
                'type' => 4,
                'sub_type' => 5,
                'name' => 'saturated',
                'aka' => null,
                'names' => null,
                'description' => 'saturated fat',
                'ref' => null,
            ],
            [
                'type' => 4,
                'sub_type' => 6,
                'name' => 'monounsaturated',
                'aka' => null,
                'names' => null,
                'description' => 'monounsaturated fat',
                'ref' => null,
            ],
            [
                'type' => 4,
                'sub_type' => 7,
                'name' => 'polyunsaturated',
                'aka' => null,
                'names' => null,
                'description' => 'polyunsaturated fat',
                'ref' => null,
            ],
            [
                'type' => 2,
                'sub_type' => null,
                'name' => 'sugar',
                'aka' => null,
                'names' => null,
                'description' => 'General sugar',
                'ref' => null,
            ],
            [
                'type' => 4,
                'sub_type' => null,
                'name' => 'fat',
                'aka' => null,
                'names' => null,
                'description' => 'General fat',
                'ref' => null,
            ],
            [
                'type' => 4,
                'sub_type' => 7,
                'name' => 'omega3',
                'aka' => null,
                'names' => json_encode(['EPA', 'DHA', 'ALA']),
                'description' => 'When it comes to fat, there\'s one type you don’t want to cut back on: omega-3 fatty acids. Two crucial ones -- EPA and DHA -- are primarily found in certain fish. ALA (alpha-linolenic acid), another omega-3 fatty acid, is found in plant sources such as nuts and seeds. Not only does your body need these fatty acids to function, but also they deliver some big health benefits.',
                'ref' => 'https://www.webmd.com/healthy-aging/omega-3-fatty-acids-fact-sheet#1',
            ],
            [
                'type' => 4,
                'sub_type' => 6,
                'name' => 'omega9',
                'aka' => null,
                'names' => null,
                'description' => 'Omega-9 fatty acids are from a family of unsaturated fats that are commonly found in vegetable and animal fats. These fatty acids are also known as oleic acid, or monounsaturated fats, and can often be found in canola oil, safflower oil, olive oil, mustard oil, nut oils and, nuts such as almonds.',
                'ref' => null,
            ],
            [
                'type' => 4,
                'sub_type' => 10,
                'name' => 'fatty-acids',
                'aka' => null,
                'names' => null,
                'description' => 'Fatty acids are the basic building blocks of lipids or fats. One of the ways fatty acids are classified is by the number of carbon atoms in their tails. Long-chain fatty acids are those with 14 or more carbons. They\'re found in most fats and oils, including olive oil, soybean oil, fish, nuts, avocado and meat.',
                'ref' => null,
            ],
            [
                'type' => 6,
                'sub_type' => 11,
                'name' => 'a',
                'aka' => 'beta-carotene',
                'names' => null,
                'description' => 'Vitamin A is a fat-soluble vitamin that is naturally present in many foods. Vitamin A is important for normal vision, the immune system, and reproduction. Vitamin A also helps the heart, lungs, kidneys, and other organs work properly.\n\nThere are two different types of vitamin A. The first type, preformed vitamin A, is found in meat, poultry, fish, and dairy products. The second type, provitamin A, is found in fruits, vegetables, and other plant-based products. The most common type of provitamin A in foods and dietary supplements is beta-carotene.',
                'ref' => 'https://ods.od.nih.gov/factsheets/VitaminA-Consumer/',
            ],
            [
                'type' => 6,
                'sub_type' => 11,
                'name' => 'd',
                'aka' => null,
                'names' => null,
                'description' => 'Vitamin D is a nutrient found in some foods that is needed for health and to maintain strong bones. It does so by helping the body absorb calcium (one of bone’s main building blocks) from food and supplements. People who get too little vitamin D may develop soft, thin, and brittle bones, a condition known as rickets in children and osteomalacia in adults.\n\nVitamin D is important to the body in many other ways as well. Muscles need it to move, for example, nerves need it to carry messages between the brain and every body part, and the immune system needs vitamin D to fight off invading bacteria and viruses. Together with calcium, vitamin D also helps protect older adults from osteoporosis. Vitamin D is found in cells throughout the body.',
                'ref' => 'https://ods.od.nih.gov/factsheets/VitaminD-Consumer/',
            ],
            [
                'type' => 6,
                'sub_type' => 11,
                'name' => 'e',
                'aka' => null,
                'names' => null,
                'description' => 'Vitamin E is a fat-soluble nutrient found in many foods. In the body, it acts as an antioxidant, helping to protect cells from the damage caused by free radicals. Free radicals are compounds formed when our bodies convert the food we eat into energy. People are also exposed to free radicals in the environment from cigarette smoke, air pollution, and ultraviolet light from the sun.\n\nThe body also needs vitamin E to boost its immune system so that it can fight off invading bacteria and viruses. It helps to widen blood vessels and keep blood from clotting within them. In addition, cells use vitamin E to interact with each other and to carry out many important functions.',
                'ref' => 'https://ods.od.nih.gov/factsheets/VitaminE-Consumer/',
            ],
            [
                'type' => 6,
                'sub_type' => 11,
                'name' => 'k',
                'aka' => null,
                'names' => null,
                'description' => 'Vitamin K is a nutrient that the body needs to stay healthy. It’s important for blood clotting and healthy bones and also has other functions in the body.',
                'ref' => 'https://ods.od.nih.gov/factsheets/VitaminK-Consumer/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b1',
                'aka' => 'thiamin',
                'names' => null,
                'description' => 'Thiamin, or vitamin B1, helps to release energy from foods, promotes normal appetite, and is important in maintaining proper nervous system function.\n\nFood Sources for Thiamin. Sources include peas, pork, liver, and legumes. Most commonly, thiamin is found in whole grains and fortified grain products such as cereal, and enriched products like bread, pasta, rice, and tortillas. The process of enrichment adds back nutrients that are lost when grains are processed. Among the nutrients added during the enrichment process are thiamin (B1), niacin (B3), riboflavin (B2), folate and iron.\n\nHow much Thiamin. The Recommended Dietary Allowance (RDA) for thiamin is 1.2 mg/day for adult males and 1.1 mg/day for adult females (Table 1). These values are closely tied to calorie expenditure.\n\nThiamin Deficiency. Under-consumption of thiamin is rare in the United States due to wide availability of enriched grain products. However, low calorie diets as well as diets high in refined and processed carbohydrates may place one at risk for thiamin deficiency. Alcoholics are especially prone to thiamin deficiency because excess alcohol consumption often replaces food or meals. Symptoms of thiamin deficiency include: mental confusion, muscle weakness, wasting, water retention (edema), impaired growth, and the disease known as beriberi. Thiamin deficiency is currently not a problem in the United States.\n\nToo much Thiamin. No problems with overconsumption are known for thiamin.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b2',
                'aka' => 'riboflavin',
                'names' => null,
                'description' => 'Riboflavin, or vitamin B2, helps to release energy from foods, promotes good vision, and healthy skin. It also helps to convert the amino acid tryptophan (which makes up protein) into niacin.\n\nFood Sources for Riboflavin. Sources include liver, eggs, dark green vegetables, legumes, whole and enriched grain products, and milk. Ultraviolet light is known to destroy riboflavin, which is why most milk is packaged in opaque containers instead of clear.\n\nHow much Riboflavin. The Recommended Dietary Allowance (RDA) for riboflavin is 1.3 mg/day for adult males and 1.1 mg/day for adult females (Table 1). Like thiamin, these values are closely tied to energy expenditure.\n\nRiboflavin Deficiency. Under consumption of riboflavin is rare in the United States. However, it has been known to occur with alcoholism, malignancy, hyperthyroidism, and in the elderly. Symptoms of deficiency include cracks at the corners of the mouth, dermatitis on nose and lips, light sensitivity, cataracts, and a sore, red tongue.\n\nToo much Riboflavin. No problems with overconsumption are known for riboflavin.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b3',
                'aka' => 'niacin',
                'names' => json_encode(['Nicotinamide', 'Nicotinic Acid']),
                'description' => 'Niacin, or vitamin B3, is involved in energy production, normal enzyme function, digestion, promoting normal appetite, healthy skin, and nerves.\n\nFood Sources for Niacin. Sources include liver, fish, poultry, meat, peanuts, whole and enriched grain products.\n\nHow much Niacin. The Recommended Dietary Allowance (RDA) for niacin is 16 mg/day for adult males and 14 mg/day for adult females (Table 1). These values are closely tied to energy expenditure.\n\nNiacin Deficiency. Niacin deficiency is not a problem in the United States. However, it is known to occur with alcoholism, protein malnourishment, low calorie diets, and diets high in refined carbohydrates. Pellagra is the disease state that occurs as a result of severe niacin deficiency. Symptoms include cramps, nausea, mental confusion, and skin problems.\n\nToo much Niacin. Consuming large doses of niacin supplements may cause flushed skin, rashes, or liver damage (Table 2). Over consumption of niacin is not a problem if it is obtained through food.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b6',
                'aka' => null,
                'names' => json_encode(['Pyridoxine', 'Pyridoxal', 'Pyridoxamine']),
                'description' => 'Vitamin B6, otherwise known as pyridoxine, pyridoxal or pyridoxamine, aids in protein metabolism and red blood cell formation. It is also involved in the body’s production of chemicals such as insulin and hemoglobin.\n\nFood Sources for Vitamin B6. Sources include pork, meats, whole grains and cereals, legumes, and green, leafy vegetables.\n\nHow much Vitamin B6. The Recommended Dietary Allowance (RDA) for vitamin B6 is 1.3 mg/day for adult males and females through age fifty (Table 1). For infants, breast milk and most infant formulas contain enough vitamin B6.\n\nVitamin B6 Deficiency. Deficiency symptoms include skin disorders, dermatitis, cracks at corners of mouth, anemia, kidney stones, and nausea. A vitamin B6 deficiency in infants can cause mental confusion.\n\nToo much Vitamin B6. Over consumption is rare, but excess doses of vitamin B6 over time have been known to result in nerve damage',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b9',
                'aka' => 'folic acid',
                'names' => json_encode(['Folate', 'Folacin']),
                'description' => 'Folate, also known as folic acid or folacin, aids in protein metabolism, promoting red blood cell formation, and lowering the risk for neural tube birth defects. Folate may also play a role in controlling homocysteine levels, thus reducing the risk for coronary heart disease.\n\nFood Sources for Folate. Sources of folate include liver, kidney, dark green leafy vegetables, meats, fish, whole grains, fortified grains and cereals, legumes, and citrus fruits. Not all whole grain products are fortified with folate. Check the nutrition label to see if folic acid has been added.\n\nHow much Folate. The Recommended Dietary Allowance (RDA) for folate is 400 mcg/day for adult males and females. Pregnancy will increase the RDA for folate to 600 mcg/day (Table 1).\n\nFolate Deficiency. Folate deficiency affects cell growth and protein production, which can lead to overall impaired growth. Deficiency symptoms also include anemia and diarrhea. A folate deficiency in women who are pregnant or of child bearing age may result in the delivery of a baby with neural tube defects such as spina bifida.\n\nToo much Folate. Over consumption of folate offers no known benefits, and may mask B12 deficiency as well as interfere with some medications.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b12',
                'aka' => 'cobalamin',
                'names' => null,
                'description' => 'Vitamin B12, also known as cobalamin, aids in the building of genetic material, production of normal red blood cells, and maintenance of the nervous system.\n\nFood Sources for Vitamin B12. Vitamin B12 can only be found only in foods of animal origin such as meats, liver, kidney, fish, eggs, milk and milk products, oysters, shellfish. Some fortified foods may contain vitamin B12.\n\nHow much Vitamin B12. The Recommended Dietary Allowance (RDA) for vitamin B12 is 2.4 mcg/day for adult males and females (Table 1). For those over the age of fifty, the dietary guidelines recommend consuming vitamin B12 in its crystalline form (fortified foods or multivitamin).\n\nVitamin B12 Deficiency. Vitamin B12 deficiency most commonly affects strict vegetarians (those who eat no animal products), infants of vegan mothers, and the elderly. Symptoms of deficiency include anemia, fatigue, neurological disorders, and degeneration of nerves resulting in numbness and tingling. In order to prevent vitamin B12 deficiency, a dietary supplement should be taken. Some people develop a B12 deficiency because they cannot absorb the vitamin through their stomach lining. This can be treated through vitamin B12 injections.\n\nToo much Vitamin B12. No problems with overconsumption of vitamin B12 are known.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b7',
                'aka' => 'biotin',
                'names' => null,
                'description' => 'Biotin helps release energy from carbohydrates and aids in the metabolism of fats, proteins and carbohydrates from food.\n\nFood Sources for Biotin. Sources of Biotin include liver, kidney, egg yolk, milk, most fresh vegetables, yeast breads and cereals. Biotin is also made by intestinal bacteria.\n\nHow much Biotin. The Adequate Intake (AI) for Biotin is 30 mcg/day for adult males and females.\n\nBiotin Deficiency. Biotin deficiency is uncommon under normal circumstances, but symptoms include fatigue, loss of appetite, nausea, vomiting, depression, muscle pains, heart abnormalities and anemia.\n\nToo much Biotin. No problems with overconsumption are known for Biotin.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'b5',
                'aka' => 'pantothenic acid',
                'names' => null,
                'description' => 'Pantothenic Acid is involved in energy production, and aids in the formation of hormones and the metabolism of fats, proteins, and carbohydrates from food.\n\nFood Sources for Pantothenic Acid. Sources include liver, kidney, meats, egg yolk, whole grains, and legumes. Pantothenic Acid is also made by intestinal bacteria.\n\nHow much Pantothenic Acid. The Adequate Intake (AI) for Pantothenic Acid is 5 mg/day for both adult males and females (Table 1).\n\nPantothenic Acid Deficiency. Pantothenic Acid deficiency is uncommon due to its wide availability in most foods.\n\nToo much Pantothenic Acid. No problems with overconsumption are known for Pantothenic Acid. Rarely, diarrhea and water retention will occur with excessive amounts.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 6,
                'sub_type' => 12,
                'name' => 'c',
                'aka' => 'ascorbic acid',
                'names' => json_encode(['Ascorbate']),
                'description' => 'The body needs vitamin C, also known as ascorbic acid or ascorbate, to remain in proper working condition. Vitamin C benefits the body by holding cells together through collagen synthesis; collagen is a connective tissue that holds muscles, bones, and other tissues together. Vitamin C also aids in wound healing, bone and tooth formation, strengthening blood vessel walls, improving immune system function, increasing absorption and utilization of iron, and acting as an antioxidant.\n\nSince our bodies cannot produce or store vitamin C, an adequate daily intake of this nutrient is essential for optimum health. Vitamin C works with vitamin E as an antioxidant, and plays a crucial role in neutralizing free radicals throughout the body. An antioxidant can be a vitamin, mineral, or a carotenoid, present in foods, that slows the oxidation process and acts to repair damage to cells of the body. Studies suggest that vitamin C may reduce the risk of certain cancers, heart disease, and cataracts. Research continues to document the degree of these effects.\n\nFood Sources for Vitamin C. Consuming vitamin C-rich foods is the best method to ensure an adequate intake of this vitamin. While many common plant foods contain vitamin C, the best sources are citrus fruits. For example, one orange, a kiwi fruit, 6 oz. of grapefruit juice or 1/3 cup of chopped sweet red pepper each supply enough vitamin C for one day.\n\nHow much Vitamin C. The Recommended Dietary Allowance (RDA) for Vitamin C is 90 mg/day for adult males and 75 mg/day for adult females (Table 1). For those who smoke cigarettes, the RDA for vitamin C increases by 35 mg/day, in order to counteract the oxidative effects of nicotine.\n\nVitamin C Deficiency. Although rare in the United States, severe vitamin C deficiency may result in the disease known as scurvy, causing a loss of collagen strength throughout the body. Loss of collagen results in loose teeth, bleeding and swollen gums, and improper wound healing. More commonly, vitamin C deficiency presents as a secondary deficiency in alcoholics, the elderly, and in smokers.\n\nThe following conditions have been shown to increase vitamin C requirements (Table 1):\n\nEnvironmental stress, such as air and noise pollution\nUse of certain drugs, such as oral contraceptives\nTissue healing of wounds\nGrowth (children from 0- 12 months, and pregnant women)\nFever and infection\nSmoking.\nToo Much Vitamin C. Despite being a water-soluble vitamin that the body excretes when in excess, vitamin C overdoses have been shown to cause kidney stones, gout, diarrhea, and rebound scurvy.',
                'ref' => 'http://extension.colostate.edu/topic-areas/nutrition-food-safety-health/water-soluble-vitamins-b-complex-and-vitamin-c-9-312/',
            ],
            [
                'type' => 5,
                'sub_type' => 13,
                'name' => 'calcium',
                'aka' => 'Ca',
                'names' => null,
                'description' => 'Calcium is probably best known for preventing osteoporosis, but it\'s necessary for much more than strong bones and teeth. Your body also needs calcium for blood clotting and normal nervous system and muscle function.\n\nIn general, a healthy diet includes an ample amount of calcium. People with some disorders, however, such as inflammatory bowel disease may not absorb enough of this mineral. Those who are on corticosteroids for autoimmune conditions or asthma may similarly lack enough calcium. In addition, those who have a milk allergy or lactose intolerance may need to make sure they are getting calcium from other foods.\n\nCalcium is found in the largest amounts in dairy products, such as milk, cheese, and yogurt. But if you aren\'t a milk drinker, there are plenty of other foods which contain calcium. Calcium is also found in nuts, green leafy vegetables, and fortified foods such as breakfast cereal. \n\nCalcium supplements are one of the most popular dietary supplements and may be recommended for some people, especially postmenopausal women. But it\'s important to talk to your doctor, as elevated levels can cause problems such as painful kidney stones.\n\nSupplements are not recommended for people with some medical conditions, and they may also interact with some medications.',
                'ref' => 'https://www.verywellfit.com/what-are-the-major-minerals-2507750',
            ],
            [
                'type' => 5,
                'sub_type' => 13,
                'name' => 'cloride',
                'aka' => 'Cl',
                'names' => null,
                'description' => 'Chloride is an interesting major mineral. Your body needs it to create gastric juices and it\'s found right alongside sodium in the fluid surrounding the cells. In fact, chloride works together with sodium to help keep your body fluids in balance. \n\nDietary chloride is found in table salt (sodium chloride) and many vegetables, including celery and tomatoes. There\'s rarely any reason to take chloride supplements.',
                'ref' => 'https://www.verywellfit.com/what-are-the-major-minerals-2507750',
            ],
            [
                'type' => 5,
                'sub_type' => 13,
                'name' => 'magnesium',
                'aka' => 'Mg',
                'names' => null,
                'description' => 'Magnesium is necessary for biochemical functions that control many actions in your body, including proper muscle contractions and nerve impulses. It\'s also necessary for blood sugar control, regulation of blood pressure, and maintaining healthy strong bones. \n\nMagnesium deficiency is uncommon, but certain medical conditions can predispose a person to low levels. Gastrointestinal conditions such as Crohn\'s disease and celiac disease, alcohol abuse, and diabetes may cause a deficiency. Some medications (such as antibiotics and diuretics) can also lead to a deficiency.\n\nSymptoms of magnesium deficiency can be uncomfortable and may include fatigue, weakness, numbness or tingling in your arms and legs, muscle cramps, and abnormal heart rhythms. Severe magnesium deficiency can also lead to deficiencies in calcium and potassium as well.\n\nMagnesium is found primarily in nuts, seeds, whole grains, legumes and dark green vegetables. It\'s also found in yogurt, salmon, fortified breakfast cereal, bananas, and potatoes.\n\nAlthough magnesium deficiency appears to be rare, magnesium supplements are fairly common and are often combined with calcium. Magnesium supplements have sometimes been recommended for the prevention of migraines or for the relief of minor anxiety, but again, it\'s important to talk with your doctor first.​\n\nWhile a deficiency of magnesium can cause symptoms, getting too much magnesium (usually by way of supplements) can lead to nausea, diarrhea, a change in mental status, and other symptoms.',
                'ref' => 'https://www.verywellfit.com/what-are-the-major-minerals-2507750',
            ],
            [
                'type' => 5,
                'sub_type' => 13,
                'name' => 'phosphorus',
                'aka' => 'P',
                'names' => null,
                'description' => 'Phosphorus is important for bone growth and normal cell membrane function. It works along with B-complex vitamins to convert the foods you eat into energy that your body needs for all your daily activities. It is stored in bones.\n\nA  deficiency of phosphorus is relatively uncommon and is usually associated with medications such as calcium carbonate supplements and antacids. A deficiency severe enough to cause symptoms is rare, and typically only happens with extreme malnutrition.\n\nPhosphorus is found in foods that are high in protein such as meats, nuts, seeds, and legumes.\n\nTaking phosphorus supplements isn\'t necessary, and, in contrast, an excess amount of phosphorus is actually linked to a higher risk of death overall. Phosphorus toxicity (too much phosphorus) is very uncommon but has been found with conditions such as severe kidney disease.',
                'ref' => 'https://www.verywellfit.com/what-are-the-major-minerals-2507750',
            ],
            [
                'type' => 5,
                'sub_type' => 13,
                'name' => 'potasium',
                'aka' => 'K',
                'names' => null,
                'description' => 'Potassium is needed for normal nervous system function, muscle contraction, and can have a profound effect on your health. Proper levels of potassium are also extremely important in maintaining a normal heart rhythm, and either a deficiency or excess of this mineral can result in life-threatening arrhythmias or respiratory failure.\n\nPotassium is found in the fluid inside your cells so it\'s essential for normal fluid balance throughout your body. Potassium can also counteract the impact of sodium on blood pressure.\n\nEither a high or a low level of potassium can result in problems. A low potassium level (hypokalemia) can result in dangerous arrhythmias, and usually requires intervenous potassium in the ICU if levels are seriously low. An elevated potassium level (hyperkalemia) can likewise cause abnormal heart rhythms. \n\nPotassium-rich foods include fruits and vegetables (such as bananas and potatoes), as well as legumes, milk, nuts, and meats. You may be able to find potassium supplements, but don\'t take them without speaking with your medical doctor first.\n\nWith kidney disease, potassium levels may need to be monitored and a low-potassium diet instituted.',
                'ref' => 'https://www.verywellfit.com/what-are-the-major-minerals-2507750',
            ],
            [
                'type' => 5,
                'sub_type' => 13,
                'name' => 'sodium',
                'aka' => 'Na',
                'names' => null,
                'description' => 'Sodium works along with chloride to maintain fluid balance outside the cells. Sodium intake is important for regulating blood pressure. Sodium deficiency is rare, and in fact, getting too much sodium is a much more widespread problem. Consuming too much sodium may elevate blood pressure in some people.\n\nSodium is found along with chloride in table salt and it\'s naturally found in small amounts in a variety of foods. But, most sodium comes from processed foods that contain salt or preservatives made with sodium. ',
                'ref' => 'https://www.verywellfit.com/what-are-the-major-minerals-2507750',
            ],
            [
                'type' => 5,
                'sub_type' => 13,
                'name' => 'sulfur',
                'aka' => 'S',
                'names' => null,
                'description' => 'Sulfur is another essential mineral that most people get enough of in their diets. That’s because our body gets sulfur from all sources of protein and many fats. However, some natural health experts, like Dr. Joseph Mercola, believe the need for sulfur may be underestimated.\n\nYour body uses sulfur for nervous system function as well as to produce healthy hair, cartilage, skin and nails.',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'zinc',
                'aka' => 'Zn',
                'names' => null,
                'description' => 'Zinc gets a lot of credit for helping promote a strong immune system. It also plays an important role in normal growth and development. Zinc even helps maintain your sense of smell and vision.\n\nFood Sources: Protein sources like meat and beans are good sources of zinc. You can also get it from whole grains, spinach and even cocoa. If you’re interested in trying a zinc supplement, try Zinc Bis-Glycinate, which is chelated to support absorption.',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'iron',
                'aka' => 'Fe',
                'names' => null,
                'description' => 'Iron is a trace mineral that is important for healthy blood. It helps red blood cells transport oxygen throughout your body, and helps carry carbon dioxide out. A deficiency in iron can lead to the condition known as anemia.\n\nFood Sources: Red meat and egg yolks are high in iron. But you can also find it in spinach, artichokes, dried fruit and mollusks. Some cereals are enriched with iron. If you need extra iron in your diet, consider an iron supplement',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'copper',
                'aka' => 'Cu',
                'names' => null,
                'description' => 'Our bodies use copper to produce connective tissues and healthy bones. One of its jobs is helping the body absorb iron.\n\nA deficiency in copper could lead to osteoporosis, joint problems and a compromised immune system. Copper can be poisonous in large amounts – which is why it’s a trace mineral – requiring just 2mg a day.\n\nFood Sources: You’ll find copper in seafood like oyster, lobster and crab. Plant sources include kale and avocado. It’s also available in nuts, seeds and mushrooms, and in supplements.',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'iodine',
                'aka' => 'I',
                'names' => null,
                'description' => 'The main role of the trace mineral iodine is promoting healthy thyroid function. It helps your body create thyroid hormones that regulate growth and metabolism. It is often combined with potassium to support thyroid health.\n\nToo much or too little iodine can lead to the conditions known as hyperthyroidism and hypothyroidism.\n\nFood Sources: Seafood as well as seaweed is the best source of iodine. It is also found in potatoes, eggs and milk.',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'selenium',
                'aka' => 'Se',
                'names' => null,
                'description' => 'Selenium is a trace mineral required for healthy heart function. It is also an antioxidant that promotes immune system strength and works with Vitamin E in your body.\n\nFood Sources: Found in most cereals, meats, fish and dairy. For plant sources, selenium is available in legumes and Brazil nuts, as well as fruits and vegetables grown where the mineral is present in the soil. You can get selenium in a supplement',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'manganese',
                'aka' => 'Mn',
                'names' => null,
                'description' => 'Manganese supports enzyme functions and helps our bodies absorb nutrients by breaking down carbohydrates and cholesterol. It’s also important for bone and joint health.\n\nFood Sources: Good sources of manganese include spinach and kale as well as black tea. You can also get manganese from beans, seafood and whole wheat bread. If your manganese levels need extra support, consider a supplement',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'chromium',
                'aka' => 'Cr',
                'names' => null,
                'description' => 'Chromium is involved with regulating blood sugar levels in our bodies as it appears to enhance insulin activity.\n\nFood Sources: Broccoli may be the best vegetable for chromium. It is also found in Brewer’s yeast, molasses, barley and oats as well as meat sources. You can get chromium supplements',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'fluoride',
                'aka' => 'F',
                'names' => null,
                'description' => 'Fluoride is used by the body in small amounts to promote bone formation as well as strong teeth. You’ve probably heard about it when it comes to things like toothpaste.\n\nThere is some controversy on fluoride found in drinking water. Read Mary Bloomer’s article on flouride for more on that.\n\nFood Sources: We typically get the trace mineral fluoride from drinking water, where it can occur naturally or is added to the water supply.',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'molybdenum',
                'aka' => 'Mo',
                'names' => null,
                'description' => 'The trace mineral molybdenum triggers enzymes in the body that help us break down proteins. It promotes normal growth and development.\n\nFood Sources: Found in milk and cheese as well as many beans and legumes. Dark green leafy vegetables provide molybdenum as do cereals and nuts. We offer a liquid molybdenum supplement',
                'ref' => 'http://blog.naturalhealthyconcepts.com/2014/03/18/major-minerals-trace-minerals/',
            ],
            [
                'type' => 5,
                'sub_type' => 14,
                'name' => 'cobalt',
                'aka' => 'Co',
                'names' => null,
                'description' => 'Required in the synthesis of vitamin B12, but because bacteria are required to synthesize the vitamin, it is usually considered part of vitamin B12 which comes from eating animals and animal-sourced foods (eggs...)',
                'ref' => 'https://en.wikipedia.org/wiki/Mineral_(nutrient)',
            ],
            [
                'type' => 7,
                'sub_type' => null,
                'name' => 'fibre',
                'aka' => null,
                'names' => null,
                'description' => 'Dietary Fibre\nWHAT IS DIETARY FIBRE?\nDietary fibre is a type of carbohydrate that cannot be digested by our bodies\' enzymes. It is found in edible plant foods such as cereals, fruits, vegetables, dried peas, nuts, lentils and grains. Fibre is grouped by its physical properties and is called soluble, insoluble or resistant starch. All three types of fibre have important roles to play.\n\nWHAT DOES FIBRE DO?\nDietary fibre helps keep the gut healthy and is important in helping to reduce the risk of diseases such as diabetes, coronary heart disease and bowel cancer2. Fibre reaches the large bowel undigested where it is fermented by bacteria. The by-products of this fermentation are carbon dioxide, methane, hydrogen and short-chain fatty acids (SCFAs). The SCFAs are used by the body. Initially, increasing fibre intake can cause an increase in gas production which can result in bloating. However, depending on the type of fibre chosen, our bodies do adapt and gas production for most people should decrease over time. Soluble fibre and resistant starch also function as prebiotics and support the probiotics (bacteria) we have in our large bowel which are essential for digestive health.\n\nWHERE ARE THE DIFFERENT TYPES OF FIBRE FOUND?\nSoluble fibre is found in foods like fruit, oats, beans and barley. When it dissolves in water it forms a gel-like substance. Soluble fibre helps to:\n\nSupport the growth of friendly bacteria needed to help maintain a healthy gut\nReduce cholesterol absorption by binding to it in the gut\nSlow down the time it takes for food to pass through the stomach into the small intestine This helps slow down the absorption of glucose into the bloodstream and has the benefits of keeping you feeling fuller for longer, helping to control blood sugar levels, which are important for the management of diabetes\nResistant Starch develops during the heating and then cooling of some foods such as potato and rice. Some grains and grain products have been developed for their high resistant starch levels and these include Hi-maize and BARLEYmaxTM. Foods high in resistant starch often have a low glycaemic index.\n\nInsoluble fibre does not dissolve in water and is found in foods like wholemeal bread, wheat bran, vegetables and nuts. Insoluble fibre adds bulk to stools by absorbing water, and helps to keep you regular. It is important to increase your fluid intake as you increase fibre. Without fluid, the fibre stays hard, making it difficult to pass and causing constipation.\nWHICH FOODS ARE RICH IN FIBRE?\nDietary fibre is found in fruits, vegetables, legumes, wholegrain breads and cereals. Most sources of dietary fibre tend to have a combination of both soluble and insoluble fibre in varying proportions. Resistant starch is not always measured when fibre is assessed in a food and we may underestimate how much fibre is present in some foods.',
                'ref' => 'https://www.nestle.co.nz/nhw/nutritionfactsheets/dietaryfibre',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'histidine',
                'aka' => 'his',
                'names' => json_encode(['H']),
                'description' => 'Histidine (symbol His or H)[2] is an α-amino acid that is used in the biosynthesis of proteins. It contains an α-amino group (which is in the protonated –NH3+ form under biological conditions), a carboxylic acid group (which is in the deprotonated –COO− form under biological conditions), and an imidazole side chain (which is partially protonated), classifying it as a positively charged amino acid at physiological pH. Initially thought essential only for infants, longer-term studies have shown it is essential for adults also.[3] It is encoded by the codons CAU and CAC.\n\nHistidine was first isolated by German physician Albrecht Kossel and Sven Hedin in 1896.[4] It is also a precursor to histamine, a vital inflammatory agent in immune responses. The acyl radical is histidyl.',
                'ref' => 'https://en.wikipedia.org/wiki/Histidine',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'isoleucine',
                'aka' => 'ile',
                'names' => json_encode(['I']),
                'description' => 'Isoleucine (symbol Ile or I)[1] is an α-amino acid that is used in the biosynthesis of proteins. It contains an α-amino group (which is in the protonated −NH+\n3 form under biological conditions), an α-carboxylic acid group (which is in the deprotonated −COO− form under biological conditions), and a hydrocarbon side chain, classifying it as a non-polar, uncharged (at physiological pH), aliphatic amino acid. It is essential in humans, meaning the body cannot synthesize it, and must be ingested in our diet. Isoleucine is synthesized from pyruvate employing leucine biosynthesis enzymes in other organisms such as bacteria.[2] It is encoded by the codons ATT, ATC, ATA.\n\nInability to break down isoleucine, along with other amino acids, is associated with the disease called Maple Syrup Urine Disease, which results in discoloration and a sweet smell in the patient\'s urine, which is where the name comes from. However, in severe cases, MSUD can lead to damage to the brain cells and ultimately death.',
                'ref' => 'https://en.wikipedia.org/wiki/Isoleucine',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'leucine',
                'aka' => 'leu',
                'names' => json_encode(['L']),
                'description' => 'Leucine (symbol Leu or L)[2] is an essential amino acid that is used in the biosynthesis of proteins. Leucine is an α-amino acid, meaning it contains an α-amino group (which is in the protonated −NH3+ form under biological conditions), an α-carboxylic acid group (which is in the deprotonated −COO− form under biological conditions), and a side chain isobutyl group, making it a non-polar aliphatic amino acid. It is essential in humans, meaning the body cannot synthesize it: it must be obtained from the diet. Human dietary sources are foods that contain protein, such as meats, dairy products, soy products, and beans and other legumes. It is encoded by the codons UUA, UUG, CUU, CUC, CUA, and CUG.\n\nLike valine and isoleucine, leucine is a branched-chain amino acid. The primary metabolic end products of leucine metabolism are acetyl-CoA and acetoacetate; consequently, it is one of the two exclusively ketogenic amino acids, with lysine being the other.[3] It is the most important ketogenic amino acid in humans.[4]p. 101\n\nLeucine and β-hydroxy β-methylbutyric acid, a minor leucine metabolite, exhibit pharmacological activity in humans and have been demonstrated to promote protein biosynthesis via the phosphorylation of the mechanistic target of rapamycin (mTOR).[5][6]',
                'ref' => 'https://en.wikipedia.org/wiki/Leucine',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'lysine',
                'aka' => 'lys',
                'names' => json_encode(['K']),
                'description' => 'Lysine plays several roles in humans, most importantly proteinogenesis, but also in the crosslinking of collagen polypeptides, uptake of essential mineral nutrients, and in the production of carnitine, which is key in fatty acid metabolism. Lysine is also often involved in histone modifications, and thus, impacts the epigenome. The ε-amino group often participates in hydrogen bonding and as a general base in catalysis. The ε-ammonium group (NH3+) is attached to the fourth carbon from the α-carbon, which is attached to the carboxyl (C=OOH) group.[2]\n\nDue to its importance in several biological processes, a lack of lysine can lead to several disease states including defective connective tissues, impaired fatty acid metabolism, anaemia, and systemic protein-energy deficiency. In contrast, an overabundance of lysine, caused by ineffective catabolism, can cause severe neurological issues.',
                'ref' => 'https://en.wikipedia.org/wiki/Lysine',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'methionine',
                'aka' => 'met',
                'names' => json_encode(['M']),
                'description' => 'Methionine (symbol Met or M)[3] (/mɪˈθaɪəniːn/)[4] is an essential amino acid in humans. As the substrate for other amino acids such as cysteine and taurine, versatile compounds such as SAM-e, and the important antioxidant glutathione, methionine plays a critical role in the metabolism and health of many species, including humans. It is encoded by the codon AUG.\n\nMethionine is also an important part of angiogenesis, the growth of new blood vessels. Supplementation may benefit those suffering from copper poisoning.[5] Overconsumption of methionine, the methyl group donor in DNA methylation, is related to cancer growth in a number of studies.[6][7] Methionine was first isolated in 1921 by John Howard Mueller.[8]',
                'ref' => 'https://en.wikipedia.org/wiki/Methionine',
            ],
            [
                'type' => 3,
                'sub_type' => 19,
                'name' => 'cysteine',
                'aka' => 'cys',
                'names' => json_encode(['C']),
                'description' => 'Cysteine (symbol Cys or C;[3] /ˈsɪstiiːn/)[4] is a semi-essential[5] proteinogenic amino acid with the formula HO2CCH(NH2)CH2SH. The thiol side chain in cysteine often participates in enzymatic reactions, as a nucleophile. The thiol is susceptible to oxidation to give the disulfide derivative cystine, which serves an important structural role in many proteins. When used as a food additive, it has the E number E920. It is encoded by the codons UGU and UGC.\n\nCysteine has the same structure as serine, but with one of its oxygen atoms replaced by sulfur; replacing it with selenium gives selenocysteine. (Like other natural proteinogenic amino acids cysteine has (L) chirality in the older D/L notation based on homology to D and L glyceraldehyde. In the newer R/S system of designating chirality, based on the atomic numbers of atoms near the asymmetric carbon, cysteine (and selenocysteine) have R chirality, because of the presence of sulfur (resp. selenium) as a second neighbor to the asymmetric carbon. The remaining chiral amino acids, having lighter atoms in that position, have S chirality.)',
                'ref' => 'https://en.wikipedia.org/wiki/Cysteine',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'phenylalanine',
                'aka' => 'phe',
                'names' => json_encode(['F']),
                'description' => 'Phenylalanine (symbol Phe or F)[2] is an α-amino acid with the formula C\n9H\n11NO\n2. It can be viewed as a benzyl group substituted for the methyl group of alanine, or a phenyl group in place of a terminal hydrogen of alanine. This essential amino acid is classified as neutral, and nonpolar because of the inert and hydrophobic nature of the benzyl side chain. The L-isomer is used to biochemically form proteins, coded for by DNA. Phenylalanine is a precursor for tyrosine, the monoamine neurotransmitters dopamine, norepinephrine (noradrenaline), and epinephrine (adrenaline), and the skin pigment melanin. It is encoded by the codons UUU and UUC.\n\nPhenylalanine is found naturally in the breast milk of mammals. It is used in the manufacture of food and drink products and sold as a nutritional supplement for its reputed analgesic and antidepressant effects. It is a direct precursor to the neuromodulator phenethylamine, a commonly used dietary supplement. As an essential amino acid, phenylalanine is not synthesized de novo in humans and other animals, who must ingest phenylalanine or phenylalanine-containing proteins.',
                'ref' => 'https://en.wikipedia.org/wiki/Phenylalanine',
            ],
            [
                'type' => 3,
                'sub_type' => 19,
                'name' => 'tyrosine',
                'aka' => 'tyr',
                'names' => json_encode(['Y']),
                'description' => 'Tyrosine (symbol Tyr or Y)[1] or 4-hydroxyphenylalanine is one of the 20 standard amino acids that are used by cells to synthesize proteins. It is a non-essential amino acid with a polar side group. The word \"tyrosine\" is from the Greek tyros, meaning cheese, as it was first discovered in 1846 by German chemist Justus von Liebig in the protein casein from cheese.[2][3] It is called tyrosyl when referred to as a functional group or side chain. While tyrosine is generally classified as a hydrophobic amino acid, it is more hydrophilic than phenylalanine.[4] It is encoded by the codons UAC and UAU.',
                'ref' => 'https://en.wikipedia.org/wiki/Tyrosine',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'threonine',
                'aka' => 'thr',
                'names' => json_encode(['T']),
                'description' => 'Threonine (symbol Thr or T)[2] is an amino acid that is used in the biosynthesis of proteins. It contains an α-amino group (which is in the protonated −NH+\n3 form under biological conditions), a carboxyl group (which is in the deprotonated −COO− form under biological conditions), and a side chain containing a hydroxyl group, making it a polar, uncharged amino acid. It is essential in humans, meaning the body cannot synthesize it: it must be obtained from the diet. Threonine is synthesized from aspartate in bacteria such as E. coli.[3] It is encoded by all the codons starting AC (ACT, ACC, ACA, and ACG).\n\nThreonine sidechains are often hydrogen bonded; the most common small motifs formed are based on interactions with serine: ST turns, ST motifs (often at the beginning of alpha helices) and ST staples (usually at the middle of alpha helices).',
                'ref' => 'https://en.wikipedia.org/wiki/Threonine',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'tryptophan',
                'aka' => 'trp',
                'names' => json_encode(['W']),
                'description' => 'Tryptophan (symbol Trp or W)[2] is an α-amino acid that is used in the biosynthesis of proteins. It contains an α-amino group, an α-carboxylic acid group, and a side chain indole, making it a non-polar aromatic amino acid. It is essential in humans, meaning the body cannot synthesize it: it must be obtained from the diet. Tryptophan is also a precursor to the neurotransmitter serotonin and the hormone melatonin.[3] It is encoded by the codon UGG.\n\nLike other amino acids, tryptophan is a zwitterion at physiological pH where the amino group is protonated (–NH3+; pKa = 9.39) and the carboxylic acid is deprotonated ( –COO−; pKa = 2.38).[4]',
                'ref' => 'https://en.wikipedia.org/wiki/Tryptophan',
            ],
            [
                'type' => 3,
                'sub_type' => 18,
                'name' => 'valine',
                'aka' => 'val',
                'names' => json_encode(['V']),
                'description' => 'Valine (symbol Val or V)[3] is an α-amino acid that is used in the biosynthesis of proteins. It contains an α-amino group (which is in the protonated −NH3+ form under biological conditions), an α-carboxylic acid group (which is in the deprotonated −COO− form under biological conditions), and a side chain isopropyl group, making it a non-polar aliphatic amino acid. It is essential in humans, meaning the body cannot synthesize it: it must be obtained from the diet. Human dietary sources are foods that contain protein, such as meats, dairy products, soy products, beans and legumes. It is encoded by all codons starting with GU (GUU, GUC, GUA, and GUG).\n\nLike leucine and isoleucine, valine is a branched-chain amino acid. In sickle-cell disease, a single glutamic acid in β-globin is replaced with valine. Because valine is hydrophobic, whereas glutamic acid is hydrophilic, this change makes the hemoglobin prone to abnormal aggregation.',
                'ref' => 'https://en.wikipedia.org/wiki/Valine',
            ],
            [
                'type' => 3,
                'sub_type' => 19,
                'name' => 'taurine',
                'aka' => null,
                'names' => null,
                'description' => 'Taurine (/ˈtɔːriːn/), or 2-aminoethanesulfonic acid, is an organic compound that is widely distributed in animal tissues.[1] It is a major constituent of bile and can be found in the large intestine, and accounts for up to 0.1% of total human body weight. Taurine is named after the Latin taurus (a cognate of the Greek ταῦρος) which means bull or ox, as it was first isolated from ox bile in 1827 by German scientists Friedrich Tiedemann and Leopold Gmelin.[2]\n\nTaurine has many fundamental biological roles, such as conjugation of bile acids, antioxidation, osmoregulation, membrane stabilization, and modulation of calcium signaling. It is essential for cardiovascular function, and development and function of skeletal muscle, the retina, and the central nervous system. Taurine is a common additive to energy drinks, which are often promoted as such.\n\nTaurine is unusual among biological molecules in being a sulfonic acid, while the vast majority of biologically occurring acids contain the more weakly acidic carboxyl group. While taurine is sometimes called an amino acid, and indeed is an acid containing an amino group, it is not an amino acid in the usual biochemical meaning of the term, which refers to those compounds containing both an amino and a carboxyl group attached to the first (alpha-) carbon atom.[3]',
                'ref' => 'https://en.wikipedia.org/wiki/Taurine',
            ],
            [
                'type' => 3,
                'sub_type' => 19,
                'name' => 'arginine',
                'aka' => 'arg',
                'names' => json_encode(['R']),
                'description' => 'Arginine (symbol Arg or R)[1] is an α-amino acid that is used in the biosynthesis of proteins.[2] It contains an α-amino group, an α-carboxylic acid group, and a side chain consisting of a 3-carbon aliphatic straight chain ending in a guanidino group. At physiological pH, the carboxylic acid is deprotonated (−COO−), the amino group is protonated (−NH3+), and the guanidino group is also protonated to give the guanidinium form (-C-(NH2)2+), making arginine a charged, aliphatic amino acid.[3] It is the precursor for the biosynthesis of nitric oxide. It is encoded by the codons CGU, CGC, CGA, CGG, AGA, and AGG.\n\nIn humans, arginine is classified as a semiessential or conditionally essential amino acid, depending on the developmental stage and health status of the individual.[4] Preterm infants are unable to synthesize or create arginine internally, making the amino acid nutritionally essential for them.[5] Most healthy people do not need to supplement with arginine because it is a component of all protein-containing foods[6] and can be synthesized in the body from glutamine via citrulline.[7]\n\nArginine plays an important role in cell division, wound healing, removing ammonia from the body, immune function,[22] and the release of hormones.[4][23][24] It is a precursor for the synthesis of nitric oxide (NO),[25] making it important in the regulation of blood pressure.[26][27][28]',
                'ref' => 'https://en.wikipedia.org/wiki/Arginine',
            ],
        ]);
    }
}
