<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MeasuresSeeder extends Seeder
{
    public function run()
    {
        DB::table('measures')->truncate();

        DB::table('measures')->insert([
            [
                'id' => 1,
                'name' => 'gram',
                'slug' => 'g',
                'measure_type' => 'M',
                'base_id' => 1,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 2,
                'name' => 'milliliter',
                'slug' => 'ml',
                'measure_type' => 'V',
                'base_id' => 2,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 3,
                'name' => 'meter',
                'slug' => 'm',
                'measure_type' => 'L',
                'base_id' => 3,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 4,
                'name' => 'second',
                'slug' => 's',
                'measure_type' => 'T',
                'base_id' => 4,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 5,
                'name' => 'piece',
                'slug' => 'pcs',
                'measure_type' => 'C',
                'base_id' => 5,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 6,
                'name' => 'kilogram',
                'slug' => 'kg',
                'measure_type' => 'M',
                'base_id' => 1,
                'factor' => 1000.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 7,
                'name' => 'ounce',
                'slug' => 'oz',
                'measure_type' => 'M',
                'base_id' => 1,
                'factor' => 28.3495,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 8,
                'name' => 'pound',
                'slug' => 'lb',
                'measure_type' => 'M',
                'base_id' => 1,
                'factor' => 453.592,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 9,
                'name' => 'liter',
                'slug' => 'l',
                'measure_type' => 'V',
                'base_id' => 2,
                'factor' => 1000.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 10,
                'name' => 'cup',
                'slug' => 'cup',
                'measure_type' => 'V',
                'base_id' => 2,
                'factor' => 240.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 11,
                'name' => 'tablespoon',
                'slug' => 'tbsp',
                'measure_type' => 'V',
                'base_id' => 2,
                'factor' => 15.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 12,
                'name' => 'teaspoon',
                'slug' => 'tsp',
                'measure_type' => 'V',
                'base_id' => 2,
                'factor' => 5.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 13,
                'name' => 'inch',
                'slug' => 'in',
                'measure_type' => 'L',
                'base_id' => 3,
                'factor' => 0.0254,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 14,
                'name' => 'minute',
                'slug' => 'min',
                'measure_type' => 'T',
                'base_id' => 4,
                'factor' => 60.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 15,
                'name' => 'handful',
                'slug' => 'hf',
                'measure_type' => 'O',
                'base_id' => 5,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 16,
                'name' => 'pinch',
                'slug' => 'pinch',
                'measure_type' => 'O',
                'base_id' => 1,
                'factor' => 0.36,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 17,
                'name' => 'splash',
                'slug' => 'spl',
                'measure_type' => 'O',
                'base_id' => 2,
                'factor' => 6.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 18,
                'name' => 'bunch',
                'slug' => 'bch',
                'measure_type' => 'O',
                'base_id' => 5,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 19,
                'name' => '5 mins',
                'slug' => '5 mins',
                'measure_type' => 'T',
                'base_id' => 14,
                'factor' => 5.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 20,
                'name' => '30 min',
                'slug' => '30 mins',
                'measure_type' => 'T',
                'base_id' => 14,
                'factor' => 30.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 21,
                'name' => 'hour',
                'slug' => 'h',
                'measure_type' => 'T',
                'base_id' => 14,
                'factor' => 60.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 22,
                'name' => '12 hours',
                'slug' => '12 h',
                'measure_type' => 'T',
                'base_id' => 21,
                'factor' => 12.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 23,
                'name' => 'half',
                'slug' => 'half',
                'measure_type' => 'C',
                'base_id' => 5,
                'factor' => 0.5,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 24,
                'name' => 'quarter',
                'slug' => 'quarter',
                'measure_type' => 'C',
                'base_id' => 5,
                'factor' => 0.25,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
            [
                'id' => 25,
                'name' => 'branch',
                'slug' => 'branch',
                'measure_type' => 'O',
                'base_id' => 5,
                'factor' => 1.0,
                'created_at' => '2025-07-09 13:41:58',
                'updated_at' => '2025-07-09 13:41:58',
            ],
        ]);
    }
}
