<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipesSeeder extends Seeder
{
    public function run()
    {
        DB::table('recipes')->truncate();

        DB::table('recipes')->insert([
            [
                'id' => 1,
                'slug' => 'pizza',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Pizza',
                'description' => null,
                'cuisine_id' => 1,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 2,
                'slug' => 'pasta',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Pasta',
                'description' => null,
                'cuisine_id' => 1,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 3,
                'slug' => 'spaghetti',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Spaghetti',
                'description' => null,
                'cuisine_id' => 1,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 4,
                'slug' => 'risotto',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Risotto',
                'description' => null,
                'cuisine_id' => 1,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 5,
                'slug' => 'gelato',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Gelato',
                'description' => null,
                'cuisine_id' => 1,
                'dish_type_id' => 6,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 6,
                'slug' => 'tiramisu',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Tiramisu',
                'description' => null,
                'cuisine_id' => 1,
                'dish_type_id' => 6,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 7,
                'slug' => 'dumplings',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Dumplings',
                'description' => null,
                'cuisine_id' => 14,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 8,
                'slug' => 'sweet-and-sour-pork',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Sweet and Sour Pork',
                'description' => null,
                'cuisine_id' => 14,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 9,
                'slug' => 'fried-rice',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Fried Rice',
                'description' => null,
                'cuisine_id' => 14,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 10,
                'slug' => 'peking-duck',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Peking Duck',
                'description' => null,
                'cuisine_id' => 14,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 11,
                'slug' => 'kung-pao-chicken',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Kung Pao Chicken',
                'description' => null,
                'cuisine_id' => 14,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 12,
                'slug' => 'butter-chicken',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Butter Chicken',
                'description' => null,
                'cuisine_id' => 27,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 13,
                'slug' => 'biryani',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Biryani',
                'description' => null,
                'cuisine_id' => 27,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 14,
                'slug' => 'samosas',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Samosas',
                'description' => null,
                'cuisine_id' => 27,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 15,
                'slug' => 'naan',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Naan',
                'description' => null,
                'cuisine_id' => 27,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 16,
                'slug' => 'tikka-masala',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Tikka Masala',
                'description' => null,
                'cuisine_id' => 27,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 17,
                'slug' => 'taco',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Taco',
                'description' => null,
                'cuisine_id' => 41,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 18,
                'slug' => 'buritto',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Burrito',
                'description' => null,
                'cuisine_id' => 41,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 19,
                'slug' => 'enchilada',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Enchilada',
                'description' => null,
                'cuisine_id' => 41,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 20,
                'slug' => 'guacamole',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Guacamole',
                'description' => null,
                'cuisine_id' => 41,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 21,
                'slug' => 'mexican-churros',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Mexican Churros',
                'description' => null,
                'cuisine_id' => 41,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 22,
                'slug' => 'sushi',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Sushi',
                'description' => null,
                'cuisine_id' => 53,
                'dish_type_id' => 17,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 23,
                'slug' => 'sashimi',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Sashimi',
                'description' => null,
                'cuisine_id' => 53,
                'dish_type_id' => 17,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 24,
                'slug' => 'ramen',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Ramen',
                'description' => null,
                'cuisine_id' => 53,
                'dish_type_id' => 15,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 25,
                'slug' => 'tempura',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Tempura',
                'description' => null,
                'cuisine_id' => 53,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 26,
                'slug' => 'miso',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Miso',
                'description' => null,
                'cuisine_id' => 53,
                'dish_type_id' => 15,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 27,
                'slug' => 'burger',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Burger',
                'description' => null,
                'cuisine_id' => 54,
                'dish_type_id' => 18,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 28,
                'slug' => 'bbq-ribs',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'BBQ Ribs',
                'description' => null,
                'cuisine_id' => 54,
                'dish_type_id' => 1,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 29,
                'slug' => 'apple-pie',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Apple Pie',
                'description' => null,
                'cuisine_id' => 54,
                'dish_type_id' => 6,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 30,
                'slug' => 'coq-au-vin',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Coq Au Vin',
                'description' => null,
                'cuisine_id' => 55,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 31,
                'slug' => 'creme-brulee',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Creme Brulee',
                'description' => null,
                'cuisine_id' => 55,
                'dish_type_id' => 6,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 32,
                'slug' => 'pad-thai',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Pad Thai',
                'description' => null,
                'cuisine_id' => 64,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 33,
                'slug' => 'green-curry',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Green Curry',
                'description' => null,
                'cuisine_id' => 64,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 34,
                'slug' => 'tom-yum',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Tom Yum',
                'description' => null,
                'cuisine_id' => 64,
                'dish_type_id' => 15,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 35,
                'slug' => 'mango-sticky-rice',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Mango Sticky Rice',
                'description' => null,
                'cuisine_id' => 64,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 36,
                'slug' => 'paella',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Paella',
                'description' => null,
                'cuisine_id' => 69,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 37,
                'slug' => 'churros',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Churros',
                'description' => null,
                'cuisine_id' => 69,
                'dish_type_id' => 2,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 38,
                'slug' => 'gazpacho',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Gazpacho',
                'description' => null,
                'cuisine_id' => 69,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 39,
                'slug' => 'jamon-iberico',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Jamon Iberico',
                'description' => null,
                'cuisine_id' => 69,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 40,
                'slug' => 'hummus',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Hummus',
                'description' => null,
                'cuisine_id' => 76,
                'dish_type_id' => 16,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 41,
                'slug' => 'falafel',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Falafel',
                'description' => null,
                'cuisine_id' => 76,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 42,
                'slug' => 'tabouleh',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Tabbouleh',
                'description' => null,
                'cuisine_id' => 76,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 43,
                'slug' => 'kimchi',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Kimchi',
                'description' => null,
                'cuisine_id' => 83,
                'dish_type_id' => 22,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 44,
                'slug' => 'bulgogi',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Bulgogi',
                'description' => null,
                'cuisine_id' => 83,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 45,
                'slug' => 'bibimbap',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Bibimbap',
                'description' => null,
                'cuisine_id' => 83,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 46,
                'slug' => 'tteokbokki',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Tteokbokki',
                'description' => null,
                'cuisine_id' => 83,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 47,
                'slug' => 'moussaka',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Moussaka',
                'description' => null,
                'cuisine_id' => 88,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 48,
                'slug' => 'souvlaki',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Souvlaki',
                'description' => null,
                'cuisine_id' => 88,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 49,
                'slug' => 'tzatziki',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Tzatziki',
                'description' => null,
                'cuisine_id' => 88,
                'dish_type_id' => 12,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 50,
                'slug' => 'baklava',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Baklava',
                'description' => null,
                'cuisine_id' => 88,
                'dish_type_id' => 23,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 51,
                'slug' => 'greek-salad',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Greek Salad',
                'description' => null,
                'cuisine_id' => 88,
                'dish_type_id' => 10,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 52,
                'slug' => 'shawarma',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Shawarma',
                'description' => null,
                'cuisine_id' => 94,
                'dish_type_id' => 18,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 53,
                'slug' => 'kebab',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Kebab',
                'description' => null,
                'cuisine_id' => 94,
                'dish_type_id' => 18,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 54,
                'slug' => 'pho',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Pho',
                'description' => null,
                'cuisine_id' => 100,
                'dish_type_id' => 15,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 55,
                'slug' => 'banh-mi',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Banh Mi',
                'description' => null,
                'cuisine_id' => 100,
                'dish_type_id' => 18,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 56,
                'slug' => 'spring-rolls',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Spring Rolls',
                'description' => null,
                'cuisine_id' => 100,
                'dish_type_id' => 11,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 57,
                'slug' => 'bun-cha',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Bun Cha',
                'description' => null,
                'cuisine_id' => 100,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 58,
                'slug' => 'baba-ganoush',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Baba Ganoush',
                'description' => null,
                'cuisine_id' => 104,
                'dish_type_id' => 13,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 59,
                'slug' => 'fattoush',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Fattoush',
                'description' => null,
                'cuisine_id' => 104,
                'dish_type_id' => 10,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 60,
                'slug' => 'risotto-lombardy',
                'variant_id' => 4,
                'author_id' => 1,
                'title' => 'Risotto',
                'description' => 'From Lombardy',
                'cuisine_id' => 2,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 61,
                'slug' => 'ossobuco',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Ossobuco',
                'description' => 'Braised veal shanks',
                'cuisine_id' => 2,
                'dish_type_id' => 24,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 62,
                'slug' => 'polenta',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Polenta',
                'description' => 'Cornmeal dish',
                'cuisine_id' => 2,
                'dish_type_id' => 11,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 63,
                'slug' => 'panna-cotta',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Panna Cotta',
                'description' => 'desert',
                'cuisine_id' => 2,
                'dish_type_id' => 6,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 64,
                'slug' => 'agnolotti',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Agnolotti',
                'description' => 'Stuffed pasta from Piedmont',
                'cuisine_id' => 2,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 65,
                'slug' => 'margherita',
                'variant_id' => 1,
                'author_id' => 2,
                'title' => 'Pizza Margherita',
                'description' => 'From Naples',
                'cuisine_id' => 3,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 66,
                'slug' => 'pasta-alla-norma',
                'variant_id' => 2,
                'author_id' => 1,
                'title' => 'Pasta alla Norma',
                'description' => 'From Sicily',
                'cuisine_id' => 3,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 67,
                'slug' => 'caponata',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Caponata',
                'description' => 'Sicilian eggplant dish',
                'cuisine_id' => 3,
                'dish_type_id' => 11,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 68,
                'slug' => 'parmigiana-di-melanzane',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Parmigiana di Melanzane',
                'description' => 'Eggplant Parmesan',
                'cuisine_id' => 3,
                'dish_type_id' => 14,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 69,
                'slug' => 'focaccia',
                'variant_id' => null,
                'author_id' => 1,
                'title' => 'Focaccia',
                'description' => 'Focaccia comes from Italy, and more specifically, its roots trace back to Liguria, the coastal region in the northwest of the country.

The Ligurian city of Genoa is especially famous for focaccia genovese — the classic flat, olive-oil-rich bread with a dimpled surface.
That said, variations of focaccia exist all over Italy:

Liguria → soft, salty, and generously oiled

Puglia → topped with tomatoes, olives, or potatoes

Veneto → sometimes sweet, more like a cake

Its origins go way back to ancient Rome (and even earlier to the Etruscans), when flatbreads baked on hearths were a staple.

',
                'cuisine_id' => 12,
                'dish_type_id' => 26,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
            [
                'id' => 70,
                'slug' => 'focaccia-barese',
                'variant_id' => 69,
                'author_id' => 1,
                'title' => 'Focaccia Barese',
                'description' => 'In Puglia (the heel of Italy’s boot), focaccia is usually called focaccia barese — named after the city of Bari.

Here are the main details and variations:

🥖 Key traits
Dough: Often enriched with mashed potatoes in addition to flour, making it softer and fluffier.

Toppings: Cherry tomatoes (pomodorini), black or green olives, oregano, coarse sea salt, and lots of extra virgin olive oil.

Texture: Crispy edges, soft center.

Baking: Traditionally baked in heavy round pans, often in wood-fired ovens.

📜 Other names / local references
U\' fugass or u\' fugassë — in local Barese dialect.

Focaccia pugliese — a general term for the region.

Focaccia con patate — when potatoes are also used as a topping, not just in the dough.

🍅 Fun note
In Bari, it’s common to grab a slice of focaccia barese instead of a sandwich — it’s a street snack, breakfast, or lunch on the go. And in small bakeries, the focaccia is often sold by weight, not per slice.',
                'cuisine_id' => 10,
                'dish_type_id' => 26,
                'created_at' => '2025-07-09 13:41:59',
                'updated_at' => '2025-07-09 13:41:59',
            ],
        ]);
    }
}
