type: object
readOnly: true
properties:
  self:
    type: string
    description: This resource
    example: https://pifon.co.uk/api/recipe/margherita
  details:
    type: string
    description: More info about this recipe
    example: https://pifon.co.uk/api/recipe/margherita/details
  ingredients:
    type: string
    description: List of ingredients
    example: https://pifon.co.uk/api/recipe/margherita/ingredients
  directions:
    type: string
    description: Preparation directions
    example: https://pifon.co.uk/api/recipe/margherita/directions
  cuisine:
    type: string
    description: Description of cuisine
    example: https://pifon.co.uk/api/cuisine/italian-neapolitan
  type:
    type: string
    description: Description of type of the dish
    example: https://pifon.co.uk/api/dish-type/main
  author:
    type: string
    description: About author
    example: https://pifon.co.uk/api/author/world-chef
required:
  - self
  - cuisine
  - type
  - author