type: object
readOnly: true
properties:
  self:
    type: string
    description: This resource
    example: https://pifon.co.uk/api/recipes/margherita
  details:
    type: string
    description: More info about this recipe
    example: https://pifon.co.uk/api/recipes/margherita/details
  cuisine:
    type: string
    description: Description of cuisine
    example: https://pifon.co.uk/api/cuisines/italian-neapolitan
required:
  - self
  - details
  - cuisine