services:
  app:
    image: api
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - ../foodbook.uk/docker/nginx/foodbook-proxy.conf:/etc/nginx/conf.d/foodbook.conf:ro
    networks:
      - laravel-network
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-fsk", "https://localhost/api/"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mariadb:lts
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${DB_DATABASE}'
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mariadb_data:
