<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entities\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'caloriesPer100g' => [parent::class, 'caloriesPer100g', null, 16],
        "\0".parent::class."\0".'carbsPer100g' => [parent::class, 'carbsPer100g', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'fatPer100g' => [parent::class, 'fatPer100g', null, 16],
        "\0".parent::class."\0".'fiberPer100g' => [parent::class, 'fiberPer100g', null, 16],
        "\0".parent::class."\0".'halal' => [parent::class, 'halal', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'kosher' => [parent::class, 'kosher', null, 16],
        "\0".parent::class."\0".'measure' => [parent::class, 'measure', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'proteinPer100g' => [parent::class, 'proteinPer100g', null, 16],
        "\0".parent::class."\0".'shelfLifeDays' => [parent::class, 'shelfLifeDays', null, 16],
        "\0".parent::class."\0".'shelfLifeOpenedDays' => [parent::class, 'shelfLifeOpenedDays', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'tasteBitter' => [parent::class, 'tasteBitter', null, 16],
        "\0".parent::class."\0".'tasteSalty' => [parent::class, 'tasteSalty', null, 16],
        "\0".parent::class."\0".'tasteSour' => [parent::class, 'tasteSour', null, 16],
        "\0".parent::class."\0".'tasteSweet' => [parent::class, 'tasteSweet', null, 16],
        "\0".parent::class."\0".'tasteUmami' => [parent::class, 'tasteUmami', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'vegan' => [parent::class, 'vegan', null, 16],
        "\0".parent::class."\0".'vegetarian' => [parent::class, 'vegetarian', null, 16],
        'caloriesPer100g' => [parent::class, 'caloriesPer100g', null, 16],
        'carbsPer100g' => [parent::class, 'carbsPer100g', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'fatPer100g' => [parent::class, 'fatPer100g', null, 16],
        'fiberPer100g' => [parent::class, 'fiberPer100g', null, 16],
        'halal' => [parent::class, 'halal', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'kosher' => [parent::class, 'kosher', null, 16],
        'measure' => [parent::class, 'measure', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'proteinPer100g' => [parent::class, 'proteinPer100g', null, 16],
        'shelfLifeDays' => [parent::class, 'shelfLifeDays', null, 16],
        'shelfLifeOpenedDays' => [parent::class, 'shelfLifeOpenedDays', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'tasteBitter' => [parent::class, 'tasteBitter', null, 16],
        'tasteSalty' => [parent::class, 'tasteSalty', null, 16],
        'tasteSour' => [parent::class, 'tasteSour', null, 16],
        'tasteSweet' => [parent::class, 'tasteSweet', null, 16],
        'tasteUmami' => [parent::class, 'tasteUmami', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'vegan' => [parent::class, 'vegan', null, 16],
        'vegetarian' => [parent::class, 'vegetarian', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
