<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recipe extends \App\Entities\Recipe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'author' => [parent::class, 'author', null, 16],
        "\0".parent::class."\0".'cookTimeMinutes' => [parent::class, 'cookTimeMinutes', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'cuisine' => [parent::class, 'cuisine', null, 16],
        "\0".parent::class."\0".'cuisineRequest' => [parent::class, 'cuisineRequest', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'difficulty' => [parent::class, 'difficulty', null, 16],
        "\0".parent::class."\0".'directions' => [parent::class, 'directions', null, 16],
        "\0".parent::class."\0".'dishType' => [parent::class, 'dishType', null, 16],
        "\0".parent::class."\0".'forkRevenuePercent' => [parent::class, 'forkRevenuePercent', null, 16],
        "\0".parent::class."\0".'forkedFrom' => [parent::class, 'forkedFrom', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'ingredients' => [parent::class, 'ingredients', null, 16],
        "\0".parent::class."\0".'prepTimeMinutes' => [parent::class, 'prepTimeMinutes', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'publishedAt' => [parent::class, 'publishedAt', null, 16],
        "\0".parent::class."\0".'serves' => [parent::class, 'serves', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'sourceDescription' => [parent::class, 'sourceDescription', null, 16],
        "\0".parent::class."\0".'sourceUrl' => [parent::class, 'sourceUrl', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'variant' => [parent::class, 'variant', null, 16],
        'author' => [parent::class, 'author', null, 16],
        'cookTimeMinutes' => [parent::class, 'cookTimeMinutes', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'cuisine' => [parent::class, 'cuisine', null, 16],
        'cuisineRequest' => [parent::class, 'cuisineRequest', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'difficulty' => [parent::class, 'difficulty', null, 16],
        'directions' => [parent::class, 'directions', null, 16],
        'dishType' => [parent::class, 'dishType', null, 16],
        'forkRevenuePercent' => [parent::class, 'forkRevenuePercent', null, 16],
        'forkedFrom' => [parent::class, 'forkedFrom', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'ingredients' => [parent::class, 'ingredients', null, 16],
        'prepTimeMinutes' => [parent::class, 'prepTimeMinutes', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'publishedAt' => [parent::class, 'publishedAt', null, 16],
        'serves' => [parent::class, 'serves', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'sourceDescription' => [parent::class, 'sourceDescription', null, 16],
        'sourceUrl' => [parent::class, 'sourceUrl', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'variant' => [parent::class, 'variant', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
