type: object
additionalProperties: false
properties:
  name:
    type: string
    description: Slug of the master recipe
    example: Pizza
  _links:
    type: object
    readOnly: true
    properties:
      self:
        type: string
        description: This resource
        example: https://pifon.co.uk/api/recipes/pizza
required:
  - slug
  - _links