type: object
additionalProperties: false
properties:
  title:
    type: string
    description: Title of the recipe
    example: Pizza Margherita
  cuisine:
    $ref: './Cuisine.yaml'
  type:
    $ref: './thin/DishType.yaml'
  _links:
    $ref: "../links/Recipe.yaml"
required:
  - title
  - cuisine
  - type
  - _links